/*----------------------------------------------------------------------------
 *      Author: Bartlomiej Gac 2018
 *			Name:    button.h
 *      Purpose: SmP&DesignLaboratory Project
 *----------------------------------------------------------------------------
 *      
 *---------------------------------------------------------------------------*/

#ifndef buttons_h
#define buttons_h

#include "MKL46Z4.h"   /* Device header */
#include "leds.h"

#define SW1_PIN 3												/* SW1 switch is on port C - pin 3 */
#define SW3_PIN 12

/*Number of IRQ generated by PORTC_PORTD interrupt*/
#define PORTC_D_IRQ_NBR (IRQn_Type) 31					/* ToDo 5.1: Define interrupt (IRQ) number for PORTC_PORTD. See interrupt vector assignments in NVIC section of KL46 Sub-Family Reference Manual - NVIC section*/ 	

//#define button1 0												/* Button 1 is first in button_mask*/
//#define button3 1												/* Button 3 is second in button_mask */

const static uint32_t button_mask[] = {1UL << 3, 1UL << 12};  //Button 1 is Port C bit 3, button 3 is Port C bit 12

void buttons_Initialize(void);								//function that initialize buttons
void buttons_Service(void);										//buttons' interrupt service procedure
uint8_t buttons_ReturnActiveDevice(void);			//return which device is active now

#endif
